# Minimal, fast starship config
# https://starship.rs/config/

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$character"""

# Faster - don't scan for languages not in use
scan_timeout = 10

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "red"

[nodejs]
format = "[$version]($style) "
style = "green"

[rust]
format = "[$version]($style) "
style = "red"

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
